name: podcustard
description: Enjoy your podcasts right here.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  rss_dart:
    path: /Users/nick/git/open_source/dart/rss_dart
  url_launcher:
  audiofileplayer:

  built_value:
  built_collection:
  redux:
  flutter_redux:
  redux_remote_devtools:

  firebase_auth:
  google_sign_in:
  apple_sign_in:
  device_info:
  flutter_auth_buttons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner:
  built_value_generator:
  pedantic:
  test:
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo1.png
